### ISSUE TITLE
Add support for List, Set and Map attributes

### ISSUE THREAD

**Issue by mbastian** [gephi/graphstore#108]

**Comment by eduramiba** [comment]
I guess we should add consistent printing and parsing for these types too.
Are they able to contain complex object or just simple types?
Are values constrained to a single type or are they any object?

I guess we could use the following syntaxes:

For lists => Same as arrays ([1, 2, 3, 2, 1])
For sets => Same as arrays ([1, 2, 3])
For maps => Similar to interval types? JSON?

**Comment by mbastian** [comment]
I agree, can you help with this as you're the most familiar with the print/parsing code.

Only simple types are allowed as values of these collections. However, it's allowed to mix different types within a list or a set so I'm not sure how we would proceed for parsing.

**Comment by eduramiba** [comment]
Yeah I was thinking to do it myself.
Does JSON sound right? It can be convenient to users.

If the value type is not known, I guess we should infer it for each value to a few types: null, String, long (BigInteger if too big) or double (BigDecimal if too big).

Same for the key or only Strings are allowed?

**Comment by mbastian** [comment]
I finally restricted the lists to a unique type, no mixed types. For maps, keys should only be simple types (Double, Float, Long, Int, Boolean, String etc.)

I'm gonna create another issue btw about print/parse and close this one.

**Comment by eduramiba** [comment]
Great, I will assign #117 to me
