### ISSUE TITLE
Overlapping intervals aren't allowed

### ISSUE THREAD

**Issue by nlap** [gephi/graphstore#127]
I have .gexf files that previously loaded in gephi 0.9.0, but no longer load in 0.9.1

I haven't had time to dig very deeply into this, but looks like it's related to the change in interval support. It's also possible my .gexf files aren't fully valid though.

Here's an example of my file: http://pastebin.com/2zVRgrnz

And here's the error given when loading them in 0.9.1:

> java.lang.IllegalArgumentException: Overlapping intervals aren't allowed
>     at org.gephi.graph.api.types.IntervalSet.overlappingIntervallException(IntervalSet.java:282)
>     at org.gephi.graph.api.types.IntervalSet.addInner(IntervalSet.java:175)
>     at org.gephi.graph.api.types.IntervalSet.add(IntervalSet.java:70)
>     at org.gephi.graph.api.types.IntervalSet.add(IntervalSet.java:28)
>     at org.gephi.io.importer.impl.ImportContainerImpl.mergeParallelEdges(ImportContainerImpl.java:883)
>     at org.gephi.io.importer.impl.ImportContainerImpl.closeLoader(ImportContainerImpl.java:728)
>     at org.gephi.io.importer.impl.ImportControllerImpl.process(ImportControllerImpl.java:281)
>     at org.gephi.desktop.importer.DesktopImportControllerUI.finishImport(DesktopImportControllerUI.java:638)
>     at org.gephi.desktop.importer.DesktopImportControllerUI.access$200(DesktopImportControllerUI.java:102)
>     at org.gephi.desktop.importer.DesktopImportControllerUI$6.run(DesktopImportControllerUI.java:286)
> [catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)

**Comment by eduramiba** [comment]
This should be fixed in future 0.9.2 version. Can you please try now with the latest 0.9.2 snapshot? Download at https://github.com/gephi/gephi#nightly-builds
