### ISSUE TITLE
how do i use grapstore?

### ISSUE THREAD

**Issue by ArisLaode** [gephi/graphstore#137]
Hello Mr @eduramiba ... 
I'm a beginner who is studying gephi on netbeans. I have downloaded gephistore and have done the command in cmd "mvn clean install" and "mvn test". What is the next step to using graphstore? thank you

**Comment by eduramiba** [comment]
Hi, what are you trying yo achieve?

**Comment by ArisLaode** [comment]
Dear Mr @eduramiba 
I want to display the graph by inputing csv data and filter it by using force atlas 2 layout algorithm. Please give me instruction to start it. Thank you.

**Comment by eduramiba** [comment]
Oh, then you need to use the gephi toolkit instead: https://gephi.org/toolkit
https://github.com/gephi/gephi/wiki/How-to-layout-a-graph (example with force atlas 1).
