### ISSUE TITLE
Graphstore currently can't be used with the graph-streaming plugin

### ISSUE THREAD

**Issue by markfarrell** [gephi/graphstore#2]
Hi, 

I've been working on some software that constructs graphs using graphstore. I also want to 
use the graph-streaming plugin/libraries in my software, to be able to stream the graphs I'm building to Gephi clients. It seems like it is possible for me to swap out graphstore with the org.graph packages in gephi-toolkit. However, it still seems to be an issue that there are naming conflicts by having duplicate "org.graph" package names in projects from the gephi group. It also feels like it is the intention to have graphstore 'replace' org.graph in the toolkit, but hasn't been finished yet. I'm just generally confused because I don't know how efficient org.graph from the toolkit might be compared to graphstore and so on and so forth; there are differences, such as not having GraphListener and GraphEvent, which made me unable to use it in my project.

**Comment by eduramiba** [comment]
Closing old issue, graph streaming plugin was made available for Gephi 0.9.1 which includes the new graphstore.
