### ISSUE TITLE
Use long instead of double for timestamps and intervals

### ISSUE THREAD

**Issue by mbastian** [gephi/graphstore#64]

**Comment by eduramiba** [comment]
When this is done I guess TimeFormat.DOUBLE should be renamed to TimeFormat.TIMESTAMP or similar

**Comment by mbastian** [comment]
Agree, I think TimeFormat.TIMESTAMP might be confusing. I might argue that "2005-05-05" can also be called a timestamp. Also, people might get confused with the whole timestamp/interval thing. Maybe TimeFormat.EPOCH? However technically speaking EPOCH is not milliseconds but seconds and I'm not sure there's a name for epoch but in milliseconds. So maybe TimeFormat.MILLISECOND? Or keep it simple and TimeFormat.LONG?

**Comment by eduramiba** [comment]
Oh right, I think the best options would be LONG or something like NUMBER

**Comment by mbastian** [comment]
I vote for LONG I think and we'll make it clear in the documentation that this is the 64-bit epoch. We could potentially introduce a 32-bit INTEGER in the future so I think LONG make sense

**Comment by eduramiba** [comment]
Yes, also say in the documentation that parsing/printing dates assumes the epoch is in millisecond precision.

**Comment by mbastian** [comment]
One issue that I see is that Long lacks +INF and -INF, which is something useful for us to represent unbounded intervals

**Comment by eduramiba** [comment]
Right... maybe we should stick with double then. Integer representation in a double does not usually have a precision problem anyway.

**Comment by mbastian** [comment]
Yes, there's isn't anything broken per se with Double so let's not revisit that for now.
